# class Price(db.Model):
#     id = db.Column(db.String,primary_key=True)
#     stock_id = db.Column(db.String)
#     date = db.Column(db.TIMESTAMP)
#     成交股數 = db.Column(db.Float)
#     成交筆數 = db.Column(db.Float)
#     成交金額 = db.Column(db.Float)
#     開盤價 = db.Column(db.Float)
#     最高價 = db.Column(db.Float)
#     最低價 = db.Column(db.Float)
#     收盤價 = db.Column(db.Float)
#     漲跌價差 = db.Column(db.Float)
#     最後揭示買價 = db.Column(db.Float)
#     最後揭示賣價 = db.Column(db.Float)
#     最後揭示買量 = db.Column(db.Float)
#     最後揭示賣量 = db.Column(db.Float)
#     本益比 = db.Column(db.Float) 